### ISSUE TITLE
Stellarium 0.19.0 fails, version for Win64 is actually 0.19.0.1

### ISSUE THREAD

**Issue by rje6459** [Thilas/chocolatey-packages#11]
The Stellarium package fails as it is pointing to the non-existing version 0.19.0 when the Win64 executable is actually 0.19.0.1.

https://github.com/Stellarium/stellarium/releases/download/v0.19.0/stellarium-0.19.0.1-win64.exe

**Comment by Thilas** [comment]
Thanks, I just pushed an updated package (0.19.0.1).
