### ISSUE TITLE
vscodium 1.33.1 x64 Error - hashes do not match

### ISSUE THREAD

**Issue by burk96** [Thilas/chocolatey-packages#12]
Error - hashes do not match. Actual value was '14B226535885370359E25A017C2CF17A40B03AD4D8A74139094F48EE72BBCD7C'.
ERROR: Checksum for 'C:\Users\user\AppData\Local\Temp\chocolatey\vscodium\1.33.1\VSCodiumSetup-x64-1.33.1.exe' did not meet 'e1f02517fe4f48edf3b8cfb5436cf128c617d0aec7e727f528c429c72e569236' for checksum type 'sha256'.

**Comment by Thilas** [comment]
Installer seems to have change. I just pushed an updated package with new hash.
