### ISSUE TITLE
[strawberryperl] Install under $env:ChocolateyToolsLocation

### ISSUE THREAD

**Issue by tylerszabo** [Thilas/chocolatey-packages#14]
Strawberry Perl likes to install under `C:\Strawberry` which isn't much of an issue but it'd be more handy to keep it with other large binary distributions (like Chocolatey-managed Cygwin) under `C:\tools\Strawberry` (or wherever the tools dir is configured to).

From https://github.com/chocolatey/choco/wiki/HelpersReference `ChocolateyToolsLocation` is replacing `ChocolateyBinRoot`.

**Comment by Thilas** [comment]
I'll see later what I can do about this. Thanks.

**Comment by tylerszabo** [comment]
When I was experimenting with it I hit this chocolatey-community/chocolatey-coreteampackages#1291 and it's working now so I'd say very low priority ;)

**Comment by Thilas** [comment]
Strawberry Perl is installed using an MSI file and as specified in https://stackoverflow.com/a/47742523/13378382, the installation directory can be easily overriden: `choco install strawberryperl --install-arguments="INSTALLDIR=""C:\tools\Strawberry"""`.

I'm adding that in the package description. It will be displayed in the next version.
