### ISSUE TITLE
[vscodium.portable] Enable portable mode

### ISSUE THREAD

**Issue by berknam** [Thilas/chocolatey-packages#18]
In VSCode in order to [enable portable mode](https://code.visualstudio.com/docs/editor/portable#_enable-portable-mode) you need to create a 'data' folder. I think you have to do the same in VSCodium. Also be careful to not delete this folder when updating because it will contain the user settings and extensions.

If you want check out how it is done in the vscode.portable package.

**Comment by Thilas** [comment]
Thanks for the feedback. I implemented it for new installs only from now on. If the package was already installed, portable mode won't be enabled.
