### ISSUE TITLE
[procexp] Archive checksums do not match

### ISSUE THREAD

**Issue by curilla** [Thilas/chocolatey-packages#19]
It seems that the Process Explorer archive was quietly on Sysinternals and the installation of the package fails on checksums not matching.

Checksum expected: 'd6b555f233ec477fef392290182ff99f2ae3abe0d9a77c2f739bc8afaea51941'
Checksum actual: 'F151063BAE2BB7C5DF26A508BDBAA1646D531644F0FB4235A697EF1B5C5EBF81'

**Comment by Thilas** [comment]
Thanks the feedback. I just pushed a new version on Chocolatey to fix that.
