### ISSUE TITLE
Can I install Strawberry Perl 32bit?

### ISSUE THREAD

**Issue by yuki-kimoto** [Thilas/chocolatey-packages#23]
Hi, thank you for chocolatey support for Strawberry Perl.

I have a question.

Can I install Strawberry Perl 32bit using chocolatey?

**Comment by Thilas** [comment]
Hi @yuki-kimoto ,

You definitely can using the `--x86` switch (see https://docs.chocolatey.org/en-us/choco/commands/install):

```cmd
choco install strawberryperl --x86
```

**Comment by yuki-kimoto** [comment]
@Thilas 

Thank you!

I'm glad to start tests my Perl modules.
