### ISSUE TITLE
[sabnzbd] does not install sabnzbd service, also does not remove it when uninstalling.

### ISSUE THREAD

**Issue by ViperTG** [Thilas/chocolatey-packages#33]
Installer does not install sabnzbd as a service even though it states it in the output.

Reason is the install script tries to install the service using `SABnzbd-service.exe`, a file which has not existed in the package since version 3.0 of sabnzbd.

The file is not called `SABnzbd-console.exe`, parameters are the same.

I suggest updating the install and before modify script to refer to that when installing/uninstalling the service.

**Comment by Thilas** [comment]
Thanks for reporting this issue. I'll have a look.

**Comment by Thilas** [comment]
Issue is now fixed. I just pushed a new version (https://community.chocolatey.org/packages/SABnzbd/3.7.0.20221203) that includes the fix.
