### ISSUE TITLE
Configure an optional Eclipse multi-user parameter

### ISSUE THREAD

**Issue by teknowledgist** [Thilas/chocolatey-packages#4]
Most people who use Eclipse are the only user of their computer and are probably administrators.  Thus, the standard "install" of the Eclipse package works fine for them.

However, the default Eclipse configuration does not play nice with SYSTEM installs (i.e. deployments) or multi-user systems with unprivileged Eclipse users.  For example, students in a classroom.

I am not an Eclipse expert or even a user, but based on [a comment on the Eclipse forums](https://www.eclipse.org/forums/index.php/t/1080254/) and on my own testing, it is possible to use Eclipse in a good approximation to a "normal", multi-user Windows program.  A .BAT file like this:

````
@echo off

set EclipseEXE="%ProgramFiles%\Eclipse 4.7.1.20171009\eclipse\eclipse.exe"
set ECLIPSEDIR="%HOMEPATH%\eclipse"

if not exist %ECLIPSEDIR% goto createdir
goto runeclipse

:createdir
echo "Creating eclipse directory"
mkdir %ECLIPSEDIR%

:runeclipse
start "" "%EclipseEXE%" -configuration %ECLIPSEDIR%

exit
````

Will start Eclipse without attempting to write to the paths around the eclipse.exe binary (in a protected location).  As a bonus, administrators (or SYSTEM) could run the eclipse.exe directly and install plugins system-wide that would then be available to all users.  Each user should also be able to install their own choice of plugins.

The current `chocolateyinstall.ps1` pins the shortcut to the installing user's taskbar.  That could stay for administrative updating.  

If the package installation called for the multi-user option, there would need to be some additional lines in the `chocolateyInstall.ps1` to update the .bat with the correct path to `eclipse.exe`, and a shortcut on the common desktop would need to point to the .BAT.

I will try to throw together a PR when I get a chance.

Thanks.

**Comment by Thilas** [comment]
I like the idea of this multi-user option. I have already started to think about it and I can quickly provide something. So you don't have to bother with a PR (except if you want to 😉).

**Comment by Thilas** [comment]
I have added the requested option (documented on the package page). Just wait for the new version to be published and give it a try.

**Comment by teknowledgist** [comment]
Excellent!  

You might want to consider a brief explanation for the /multi-user parameter in the next version, but it works great.

Thanks.
