### ISSUE TITLE
Typo in Subtitle Edit 3.6.11

### ISSUE THREAD

**Issue by cam1170** [Thilas/chocolatey-packages#45]
```
Installing subtitleedit...
WARNING: May not be able to find 'C:\Users\cjhol\AppData\Local\Temp\chocolatey\subtitleedit\3.6.11\SubtitleEdit-3.6.11-Setup.exe'. Please use full path for executables.
ERROR: Exception calling "Start" with "0" argument(s): "The system cannot find the file specified"
The upgrade of subtitleedit was NOT successful.
```
When extracted, there is a space in the exe filename (once extracted?), which the script did not expect. `Subtitle Edit-3.6.11-Setup.exe`

**Comment by Thilas** [comment]
Installer file name changed. This is now fixed and will be available in the next published version (very soon).

**Comment by Thilas** [comment]
Here it is: https://community.chocolatey.org/packages/subtitleedit/3.6.11.20230204
