### ISSUE TITLE
Minor issue:  Old Eclipse install location file left behind on upgrade

### ISSUE THREAD

**Issue by teknowledgist** [Thilas/chocolatey-packages#5]
This is not a major issue, but I noticed that when Eclipse upgraded from 4.7.1.20171220 to 4.7.2, the text file holding the old install location was left behind in the package directory.  My submitted-but-not-yet-approved PyDev (Eclipse plugin) package is using that file to identify the location of Eclipse (or more accurately, the Chocolatey-installed Eclipse), and the current submission broke when it found two location files.  

I can adjust (and should have designed it) to only look at the latest of the `Eclipse <version>.txt` files, but I thought you might want to know about the unnecessary and potential problem file left behind.

Thanks.

**Comment by Thilas** [comment]
Thanks for the issue. This is fixed but it will apply only on next versions.
