### ISSUE TITLE
[vscodium.install] Remove unnecessary dependency

### ISSUE THREAD

**Issue by vairag22** [Thilas/chocolatey-packages#56]
**Issue:** VSCodium has an unnecessary dependency on DotNet4.5.2 package.

**Details:** 
- Since version 1.78.1, both VSCode and its fork VSCodium do not require DotNet4.5.2.
- VSCode has already removed the dependency from their package.

**Testing:** There was no difference when running VSCodium after by forcefully removing DotNot4.5.2 on my machine.

**Comment by vairag22** [comment]
I believe removing this line from vscodium.install/vscodium.install.nuspec will suffice:
`<dependency id="dotnet4.5.2" version="4.5.2.20140902" />`

Opened a PR #57. Please review.

**Comment by Thilas** [comment]
Thanks for raising this issue. It will be fixed on this other PR (#58) where I'm fixing other similar issues.
