### ISSUE TITLE
Update-Script for eclipse

### ISSUE THREAD

**Issue by umol-unibas** [Thilas/chocolatey-packages#84]
Hey @Thilas 

i found a slightly more brief way to update eclipse. Maybe you want to have a look at it?

[Link to ITS-Unibas "eclipse-update.ps1"](https://github.com/ITS-Unibas/chocolatey-internal-packages/blob/master/automatic/unibas-eclipse/update.ps1)

This is just for your information - what do you think ;)

**Comment by Thilas** [comment]
Hi @umol-unibas,
It seems to me that you were able to make the code simpler essentially because you didn't have to manage things like streams or x86 versions. For the rest, both codes look quite similar to me.
Thanks for sharing anyway!
