### ISSUE TITLE
Perl 5.39.10 is a development release and should not be the default

### ISSUE THREAD

**Issue by shawnlaffan** [Thilas/chocolatey-packages#87]
It seems the default Perl version under chocolatey is 5.39.10.  https://github.com/Thilas/chocolatey-packages/blob/55315fe829a15272f7a5d08d67c56fd10326be85/strawberryperl/strawberryperl.json#L17

The odd numbered Perl releases (5.37, 5.39 etc) are for testing and development.  It is probably useful for them to be available via chocolatey, but they should not be the default.  

I suspect the simplest fix is to update the filter so they are excluded:
https://github.com/Thilas/chocolatey-packages/blob/55315fe829a15272f7a5d08d67c56fd10326be85/strawberryperl/update.ps1#L10

**Comment by Thilas** [comment]
I didn't know about that, thanks @shawnlaffan for pointing it out. What I can do is published the odd versions as prereleases. How does that sound? And in the meantime, I'm gonna unlist the existing odd versions

**Comment by shawnlaffan** [comment]
That sounds good to me.

**Comment by Thilas** [comment]
Fixed by https://github.com/Thilas/chocolatey-packages/commit/afed170b679fbc59d6f9a936f21b6299455e6819
